### ISSUE TITLE
Materialize causes text block inputs to appear strangely

### ISSUE THREAD

**Issue by palkerecsenyi** [codeddraig/ffau#6] opened 2017-12-31 13:23 UTC
![image](https://user-images.githubusercontent.com/22198767/34461838-b56b782a-ee2d-11e7-9cc1-fb5d04137ccf.png)
Materialize replaces the Blockly textbox with its own textbox, causing a strange effect.

**Comment by tti0** [comment] 2017-12-31 15:09
This issue has been resolved by recompling Blockly. Blockly now sets the DOM CSS `backgroundColor` property of the Blockly input box to `"white"`.

Ready to close @palkerecsenyi 's approval.

Signed, @tti0

**Comment by palkerecsenyi** [comment] 2017-12-31 15:10
Issue fixed.

**Comment by tti0** [comment] 2018-01-01 09:51
The issue is not fully fixed, as hangovers from Materialize still exist in the HTML input function (eg. the border at the bottom). This will be resolved in interim release 0.1.3. I will begin work now.

**Comment by tti0** [comment] 2018-01-01 11:04
Re-resolved in release https://github.com/codeddraig/ffau/releases/tag/0.1.3.

**Closed by tti0** 2018-01-01 11:04 UTC
Labels: bug, STOP DEVELOPMENT UNTIL FIXED
